services:
  app_db:
    image: mariadb:10.4
    container_name: app_db.container
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=projekt
      - MYSQL_USER=projekt
      - MYSQL_PASSWORD=projekt
    restart: always

  app_api:
      image: node:latest
      container_name: app_api.container
      working_dir: /app
      volumes:
        - .:/app
      command: node projekt.js
      ports:
        - 8081:8081

  app_client:
    image: nginx:latest
    container_name: app_client.container
    build:
      context: './docker/client'
      dockerfile: Dockerfile
    ports:
      - 81:80
    volumes:
      - './docker/client/nginx.conf:/etc/nginx/nginx.conf'
      - '.:/var/www'
